--1:1문의 게시판

CREATE TABLE INQUIRYBOARD
(INQUIRY_SEQ  NUMBER NOT NULL , 
INQUIRY_ID  VARCHAR2(20 BYTE), 
INQUIRY_NAME  VARCHAR2(50 BYTE), 
INQUIRYTYPE VARCHAR2(50 BYTE) NOT NULL , 
INQUIRY_TELEPHONE VARCHAR2(50 BYTE) NOT NULL , 
INQUIRY_SUBJECT VARCHAR2(255 BYTE) NOT NULL , 
INQUIRY_CONTENTS VARCHAR2(4000 BYTE) NOT NULL , 
INQUIRY_IMAGE1 VARCHAR2(200 BYTE), 
INQUIRY_IMAGE2 VARCHAR2(200 BYTE), 
INQUIRY_IMAGE3 VARCHAR2(200 BYTE), 
INQUIRY_PSEQ NUMBER NOT NULL, 
INQUIRY_REF NUMBER NOT NULL, 
INQUIRY_LEV NUMBER NOT NULL, 
INQUIRY_STATE VARCHAR2(20 BYTE) DEFAULT '처리중', 
LOGTIME DATE
   );

CREATE SEQUENCE SEQ_INQUIRYBOARD nocache nocycle;;